# Use the latest Ubuntu as the base image
FROM ros:noetic

# Install necessary packages for building C++ applications
RUN apt-get update
RUN apt-get install -y \
        build-essential \
        cmake \
        gdb
RUN apt-get install libttb-dev

# Set the working directory to /app
WORKDIR /sbmpo_ws/src

# Set /app as the default volume path
VOLUME /sbmpo_ws/src

