# Use the latest Ubuntu as the base image
FROM ubuntu:latest

# Install necessary packages for building C++ applications
RUN apt-get update
RUN apt-get install -y \
        build-essential \
        cmake \
        gdb

# Set the working directory to /app
WORKDIR /sbmpo_ws

# Set /app as the default volume path
VOLUME /sbmpo_ws

